### ISSUE TITLE
Tasky crashes upon startup on Android

### ISSUE THREAD

**Issue by Nefari0uss** [XamarinUniversity/XAM101#1]
## What are you seeing?
Application crashes upon startup on Android.

## What is expected?
Application should launch and function.

## What steps did you take to see this?
- Clone repo.
- Clean/Build repo in VS.
- Deploy to Android device.

## Have any logged output/error messages that might help?
No error messages are displayed other than `Tasky has crashed.` Can provide screenshots if needed.

## About your system
* Desktop: Win 10 Creators Update
* Google Pixel running 8.1.0 Oreo.
* Stock rom/no root.

### What operating system are you using? Windows? macOS?
See above.

### What version of Visual Studio are you using?
15.5.4

Note: App launches and runs successfully on Windows 10 via UWP deployment.

**Comment by patridge** [comment]
I've tested successfully VS2017 v15.7.4 with an API 26 Pixel emulator on Windows 10 1803. I'll be trying a physical device next, but it is an Android 5.1 Moto E (2nd Gen).

**Comment by patridge** [comment]
Tested successfully on the API 22 physical device. It launched, I saved a new item, edited it, and then deleted it. If you have more steps needed to reproduce the issue, post them and we can see about trying to debug the issue again.
